Задание 4-3
Vyacheslav-TKI/Subutai pull request #13
Opened 2023-12-04 19:09 UTC by Vyacheslav-TKI

2023-12-05 08:56 UTC, MarinaPaley requested changes

2023-12-05 08:56 UTC, MarinaPaley commented on 4-3.c
> + * @return целочисленная цифра
`@return целое число`

2023-12-05 08:56 UTC, MarinaPaley commented on 4-3.c
> +int element_not_in_array(int* array, const int element, size_t length);
`contains`

2023-12-05 08:56 UTC, MarinaPaley commented on 4-3.c
> +int* get_mem_array_with_one_dimension(const int length);
`size_t`

2023-12-05 08:56 UTC, MarinaPaley commented on 4-3.c
> +    puts("insert a length a inserted arrays\n");
`colunms & rows`

2023-12-05 08:56 UTC, MarinaPaley commented on 4-3.c
> +    puts("if you fill array by youself, press 1, if you fill array by random numbers, press 2\n");
Не надо использовать _&laquo;магические константы&raquo;_ в коде. Это не только признак дурновкусия, но и источник большого числа потенциальных ошибок. Привожу некоторые источники, потребные для Вашего самообразования:
- [ru.wikipedia.org](https://ru.wikipedia.org/wiki/Магическое_число_(программирование))
- [refactoring.guru](https://refactoring.guru/ru/replace-magic-number-with-symbolic-constant)
- [pvs-studio.com](https://pvs-studio.com/ru/blog/posts/cpp/0023/)
- [habr.com](https://habr.com/ru/post/328244/)

2023-12-05 08:56 UTC, MarinaPaley commented on 4-3.c
> +
Введите отдельную переменную для нового массива.

2023-12-05 08:56 UTC, MarinaPaley commented on 4-3.c
> +int* get_mem_array(const int rows, const int cols)
`const size_t rows, const size_t cols`

2023-12-05 08:56 UTC, MarinaPaley commented on 4-3.c
> +    for (int i = 0; i < rows; i++)
`size_t`

2023-12-05 08:56 UTC, MarinaPaley commented on 4-3.c
> +        array[i] = malloc(cols * sizeof(array[0]));
`(int*)malloc(cols * sizeof(int));`

2023-12-05 08:56 UTC, MarinaPaley commented on 4-3.c
> +    int** array = malloc(rows * sizeof(*array));
```c
int** array = (int**)malloc(rows * sizeof(int*));
if (NULL == array)
{
     NULL_label();
}

2023-12-05 08:56 UTC, MarinaPaley commented on 4-3.c
> +
```c
void NULL_label()
{
        errno = ENOMEM;
        perror("Error: ");
        abort();
}

2023-12-05 08:56 UTC, MarinaPaley commented on 4-3.c
> +        if (NULL == array[i])
```c
if (NULL == array[i])
{
    NULL_label();
}

2023-12-05 08:56 UTC, MarinaPaley commented on 4-3.c
> +int find_negative_elements(int* const array, size_t rows, size_t cols)
`const int* const array`

2023-12-05 08:56 UTC, MarinaPaley commented on 4-3.c
> +    int new_index = 0;
`size_t`

2023-12-05 08:56 UTC, MarinaPaley commented on 4-3.c
> +                    break;
```c
size_t j = 0;
while( j < cols &&  (array[i][j] % 5 != 0))
{
    j++;
}

flag = (j < cols) ? 1 : 0;

2023-12-05 08:56 UTC, MarinaPaley commented on 4-3.c
> +int* get_mem_array_with_one_dimension(const int length)
`const size_t  ...`

2023-12-05 08:56 UTC, MarinaPaley commented on 4-3.c
> +    int* new_array = get_mem_array(rows, cols);
Двумерный массив

2023-12-05 08:56 UTC, MarinaPaley commented on 4-3.c
> +int *first_task(int* array, size_t rows, size_t cols)
`int **`

2023-12-05 08:56 UTC, MarinaPaley commented on 4-3.c
> +    int* mas = get_mem_array(n, m);
`int**`

2023-12-05 08:56 UTC, MarinaPaley commented on 4-3.c
> +void free_array(int* array, size_t rows)
`int**`

2023-12-05 10:17 UTC, MarinaPaley reviewed
https://replit.com/@MarinaPaley/BoilingPoshVisitor#main.c

2023-12-05 10:17 UTC, MarinaPaley commented on 4-3.c
> +#include <math.h>
Лишний

2023-12-11 07:31 UTC, BalakinaEP approved these changes

2023-12-11 07:31 UTC, BalakinaEP commented on 4-3version2.c
> +    show_array(first_array, n, m);
`    show_array(first_task(mas, n, m), n, m);`

2024-02-09 10:53 UTC, merged