Все задания 1
Vyacheslav-TKI/Subutai pull request #5
Opened 2023-09-09 11:18 UTC by I461-TKI

2023-09-12 07:29 UTC, I461-TKI commented
View only changes!

2023-09-18 08:24 UTC, MarinaPaley requested changes

2023-09-18 08:24 UTC, MarinaPaley commented on task1-1.c
> +    return a;
Можно в одной строке `return log(z+x*x)+sin(x/y)*sin(x/y);`
И, пожалуйста, добавляйте (для меня), добавляйте пробелы.

2023-09-18 08:24 UTC, MarinaPaley commented on task1-2.c
> +double sec_num(double x, double y);
Поменяйте названия своим функциям. Неговорящие!

2023-09-18 08:24 UTC, MarinaPaley commented on task1-2.c
> +    printf("In the next strings insert just non-negative or just negative numbers\n");
Следите за тем, чтобы данные, предоставленные пользователем, не стали
первым аргументом функции `printf`, поскольку это чревато уязвимостью
безопасности на основе отформатированного вывода (Сикорд, 2013).

2023-09-18 08:24 UTC, MarinaPaley commented on task1-2.c
> +    }
Не надо так! Посмотрите семинар [почему](https://www.youtube.com/watch?v=7YhRFx-oyW4).

2023-09-18 08:24 UTC, MarinaPaley commented on task1-2.c
> +}
Вы все равно не чистите введенные данные.

2023-09-18 08:24 UTC, MarinaPaley commented on task1-2.c
> +#include <string.h>
Где используется?

2023-09-18 08:24 UTC, MarinaPaley commented on task1-3.c
> +double Potential_energy(double k, double x);
используйте только один стиль именования!
![cases](https://user-images.githubusercontent.com/26978698/213406039-603bfb33-7b86-4bf1-9564-3ec22e00c4f2.jpg)
Стили программирования
[CamelCase](https://ru.wikipedia.org/wiki/CamelCase)
[snake_case](https://ru.wikipedia.org/wiki/Snake_case)

2023-09-18 08:24 UTC, MarinaPaley commented on task1-3.c
> +int is_num(double *check_param);
Уберите!

2023-09-18 08:24 UTC, MarinaPaley commented on task1-3.c
> +    printf("Insert the k value first, then the x value, all values is non-negative number\n");
Небезопасное применение `printtf`. В данном случае можно использовать `puts`.

2023-09-18 08:24 UTC, MarinaPaley commented on task1-3.c
> +#include <stdio.h>
Для этой программы ЯВНО проверьте на неотрицательное значение. Не нужно проверять ввод на то, что введена строка, а не число.

2023-09-22 08:12 UTC, MarinaPaley requested changes

2023-09-22 08:12 UTC, MarinaPaley commented on task1-1.c
> + *  @param x, y, z Являются заданными константами
Каждый параметр необходимо расписывать на своей строке. Посмотрите. как пишут [здесь](https://developer.lsst.io/cpp/api-docs.html#documentation-must-use-javadoc-style-tags)

2023-09-22 08:12 UTC, MarinaPaley commented on task1-2.c
> +double Srednee_arifmetich_cubov(double x, double y);
Для перевода на английский язык используйте словари или автоматические переводчики.

2023-09-22 08:12 UTC, MarinaPaley commented on task1-3.c
> +
а, если нет?

2023-09-22 08:12 UTC, MarinaPaley commented on task1-3.c
> +double Potential_energy(double k, double x);
Ваше наименование не похоже ни на одну из картинок!

2023-09-26 08:38 UTC, MarinaPaley requested changes

2023-09-26 08:38 UTC, MarinaPaley commented on task1-3.c
> +        printf("%s", "Insert only pozitive numbers!\n");
Сначала обработка ошибки!

2023-10-02 08:31 UTC, MarinaPaley requested changes

2023-10-02 08:31 UTC, MarinaPaley commented on task1-2.c
> +    sr_arifm_cube = arithmetic_mean_of_cubes(i, j);
[`average`](https://translate.google.com/?hl=ru&sl=ru&tl=en&text=%D1%81%D1%80%D0%B5%D0%B4%D0%BD%D0%B5%D0%B5%20%D0%B0%D1%80%D0%B8%D1%84%D0%BC%D0%B5%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5&op=translate)

2023-10-02 08:31 UTC, MarinaPaley commented on task1-2.c
>      sr_geom = geometric_mean(i, j);
[`geometric_mean`](https://translate.google.com/?hl=ru&sl=ru&tl=en&text=%D1%81%D1%80%D0%B5%D0%B4%D0%BD%D0%B5%D0%B5%20%D0%B3%D0%B5%D0%BE%D0%BC%D0%B5%D1%82%D1%80%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5&op=translate)

2023-10-02 08:31 UTC, MarinaPaley commented on task1-2.c
>      scanf("%lf", &j);
Проверяйте результат выполнения функции `scanf`

2023-10-02 08:31 UTC, MarinaPaley commented on task1-1.c
> +    return a;
Это не ошибка, но можно сразу `return ...`. В блок-схеме нужно именно так, как у Вас.

2023-10-02 08:31 UTC, MarinaPaley commented on task1-2.c
> +    scanf("%lf", &j);
Проверяйте результат функции `scanf`.

2023-10-02 08:31 UTC, MarinaPaley commented on task1-3.c
> +    scanf("%lf", &x);
Проверяйте!

2023-10-02 08:31 UTC, MarinaPaley commented on task1-3.c
> +        return 0;
1. Почему возвращаем из `main` -> `0`?
2. Если попали в этот блок, то никакого "иначе" уже нет 😢

2023-10-02 08:31 UTC, MarinaPaley commented on task1-3.c
> +int is_num(double check_param) {
Можно использовать `bool`, подключив `<stbool.h>`

2023-10-06 06:34 UTC, MarinaPaley requested changes
1-3 не исправлено. Остальное хорошо.

2023-10-10 08:24 UTC, MarinaPaley approved these changes

2023-10-10 08:24 UTC, MarinaPaley commented on task1-3.c
> +    else {
не надо `else`

2024-02-09 10:51 UTC, merged