Feature/2
Vyacheslav-TKI/Subutai pull request #7
Opened 2023-09-13 16:31 UTC by I461-TKI

Все задания 2

2023-09-25 15:49 UTC, I461-TKI commented
2-1: 
![image](https://github.com/I461-TKI/Subutai/assets/61204893/2ccbf10f-fae6-4366-b6c4-9fbc18069fed)

2023-09-25 15:51 UTC, I461-TKI commented
2-2:
![2-2](https://github.com/I461-TKI/Subutai/assets/61204893/0eabfa1e-62b5-4287-91b3-d4a91d21ee70)

2023-09-25 15:53 UTC, I461-TKI commented
2-3:
![image](https://github.com/I461-TKI/Subutai/assets/61204893/81eb7043-25a0-4d9f-b007-0028a98e20c0)

2023-09-25 15:54 UTC, I461-TKI commented
2-3:
![image](https://github.com/I461-TKI/Subutai/assets/61204893/81eb7043-25a0-4d9f-b007-0028a98e20c0)

2023-09-25 15:54 UTC, Vyacheslav-TKI commented
2-3:
![image](https://github.com/I461-TKI/Subutai/assets/61204893/81eb7043-25a0-4d9f-b007-0028a98e20c0)

2023-09-26 08:41 UTC, MarinaPaley requested changes

2023-09-26 08:41 UTC, MarinaPaley commented on task_2-1.c
> +
Уберите пустую строку. Иначе это не работает как документация.

2023-09-26 08:41 UTC, MarinaPaley commented on task_2-1.c
> +    float rebro;
Не используйте транслит!
`edge`

2023-09-26 08:41 UTC, MarinaPaley commented on task_2-1.c
> +int is_right_num(double x);
Плохое название функции. Лучше  так `is_positive(const double x);`

2023-09-26 08:41 UTC, MarinaPaley commented on task_2-1.c
> +    int formul;
Совсем непонятное имя переменной (неговорящее)

2023-09-26 08:41 UTC, MarinaPaley commented on task_2-1.c
> +    scanf("%f", &rebro);
Проверьте результат функции `scanf`. Если не равно 1 (в данном случае), то аварийно завершите программу.

2023-09-26 08:41 UTC, MarinaPaley commented on task_2-1.c
> +        printf("%s", "Insert a valid value!\n");
Ошибка и выход из программы!

2023-09-26 08:41 UTC, MarinaPaley commented on task_2-1.c
> +    else {
Соответственно, `else` не нужен.

2023-09-26 08:41 UTC, MarinaPaley commented on task_2-1.c
> +        double z = rebro*rebro*rebro;
Это все нужно убрать в отдельные функции. использовать тип `enum` (в задании написано использовать перечислимый тип). Считать по формулам только тогда, когда пользователь выбрал именно такое решение.

2023-09-26 08:41 UTC, MarinaPaley commented on task_2-1.c
> +    return 0;
`return (x > 0) ? : 1 : 0;`

2023-09-26 08:41 UTC, MarinaPaley commented on task_2-2.c
> +int main(){
Используйте функции, которые Вы сами должны написать по смыслу.

2023-09-26 08:41 UTC, MarinaPaley commented on task_2-3.c
> +/**
Все замечания, что и выше.

2023-09-26 08:41 UTC, MarinaPaley commented on task_2-1.c
> +            double x = rebro*rebro;
отдельные функции

2023-10-02 08:38 UTC, MarinaPaley requested changes

2023-10-02 08:38 UTC, MarinaPaley commented on task_2-1.c
> +    scanf("%f", &cube_edge);
Проверяйте результат `scanf`!

2023-10-02 08:38 UTC, MarinaPaley commented on task_2-1.c
> +    else{
Лишний `else`, после `abort()` программа прекратит выполнение всего. `return` не `0`!

2023-10-02 08:38 UTC, MarinaPaley commented on task_2-1.c
> +            printf("%s", "Insert a valid value!\n");
Выход из программы с `abort`!

2023-10-02 08:38 UTC, MarinaPaley commented on task_2-1.c
> +                return 0;
Не `0`!

2023-10-02 08:38 UTC, MarinaPaley commented on task_2-1.c
> +#include <stdio.h>
Попробую объяснить на лекции, или подойдите лично! В этой программе нужно использовать `enum`, не только его объявить

2023-10-02 08:38 UTC, MarinaPaley commented on task_2-2.c
> +    scanf("%f", &x);
Проверка!

2023-10-02 08:38 UTC, MarinaPaley commented on task_2-2.c
> +    printf("The value of y equals: %f", y);
Ваш класс **не должен зависеть** от конкретной реализации потока ввода-вывода. Подробнее о связности и проблемах избыточной зависимости можно прочитать в [статье Германа Горелкина на Medium](https://medium.com/german-gorelkin/low-coupling-high-cohesion-d36369fb1be9).
Принципы [**SOLID**](http://sergeyteplyakov.blogspot.com/2014/10/solid.html), а именно [**D** – The Dependency Inversion Principle (DIP)](http://sergeyteplyakov.blogspot.com/2014/09/the-dependency-inversion-principle.html) также описывают проблемы связности. В частности можно привести цитату:
> Другими словами, DIP должен бороться с признаками плохого дизайном, которые так классно сформулировал все тот же Роберт Мартин в своей исходной статье о принципе инверсии зависимостей в 1996м:
> 1. Дизайн является жестким (rigid), если его тяжело изменить, поскольку любое изменение влияет на слишком большое количество других частей системы.
> 2. Дизайн является хрупким (fragile), если при внесении изменений неожиданно ломаются другие части системы.
> 3. Дизайн является неподвижным (immobile), если код тяжело использовать повторно в другом приложении, поскольку его слишком сложно «выпутать» из текущего приложения.

По русски. Если попросили результат выполнения функции, то нужно дать ТОЛЬКО результат, а еще печать, что-то другое - НЕ НАДО!

2023-10-04 17:15 UTC, Vyacheslav-TKI commented on task_2-1.c
> +#include <stdio.h>
Так я его и использовал, смотрите последнюю функцию

2023-10-06 07:07 UTC, MarinaPaley requested changes

2023-10-06 07:07 UTC, MarinaPaley commented on task_2-1.c
> +    else{
Почему Вы не исправили?

2023-10-06 07:07 UTC, MarinaPaley commented on task_2-1.c
> +        else {
Не надо использовать `else` в данном случае. Если была ошибка, то программа в любом случае прекратит работу.

2023-10-06 07:07 UTC, MarinaPaley commented on task_2-1.c
> +                puts("Please, enter 1, 2 or 3!\n");
Где Вы используете перечислимый тип, здесь я вижу константы 1, 2, 3...

2023-10-06 07:07 UTC, MarinaPaley commented on task_2-1.c
> +            scanf("%d", &formula);
Результат функции `scanf` необходимо проверять!

2023-10-06 07:07 UTC, MarinaPaley commented on task_2-1.c
> +            puts("If you want to find face area, press '1'.\n");
Здесь написано явно 1, а нужно использовать перечислимы тип.

2023-10-06 07:07 UTC, MarinaPaley commented on task_2-1.c
> +            puts("If you want to find volume, press '3'\n");
также

2023-10-06 07:07 UTC, MarinaPaley commented on task_2-1.c
> +double formula_selection(int x, double cube_edge){
Функция у Вас возвращает... `double`. По факту всегда `0` (?)

2023-10-06 07:07 UTC, MarinaPaley commented on task_2-1.c
> +        }
а, если нет, то что?

2023-10-06 07:07 UTC, MarinaPaley commented on task_2-2.c
> +    }
а, если не выполнятся предыдущие условия?

2023-10-06 07:07 UTC, MarinaPaley commented on task_2-3.c
> +    else{
`else` не нужен.

2023-10-06 07:07 UTC, MarinaPaley commented on task_2-3.c
> +            }
Выделите функцию

2023-10-06 07:07 UTC, MarinaPaley commented on task_2-3.c
> +    if(x > 0){
`return x > 0 ? 0 : 1`'

2023-10-06 16:53 UTC, Vyacheslav-TKI commented on task_2-1.c
> +    return 0;
(expected a ';') выдается

2023-10-06 16:53 UTC, Vyacheslav-TKI commented on task_2-1.c
> +double formula_selection(int x, double cube_edge){
Почему всегда 0?

2023-10-06 16:54 UTC, Vyacheslav-TKI commented on task_2-1.c
> +        }
то return 0

2023-10-06 16:55 UTC, Vyacheslav-TKI commented on task_2-2.c
> +    }
Каким образом условие не будет выполнятся? Пользователь будет вводить комплексные числа или что то другое?

2023-10-10 07:45 UTC, MarinaPaley commented on task_2-2.c
> +    }
@Vyacheslav-TKI  Тогда зачем `if` 😵‍💫

2023-10-10 07:49 UTC, Vyacheslav-TKI commented on task_2-2.c
> +    }
@MarinaPaley По условию задачи, верхнее уравнение выполняется если а*х >=1, а нижнее если а*х < 1

2023-10-10 08:37 UTC, Vyacheslav-TKI commented
вт, 10 окт. 2023 г., 10:45 Васильева Марина Алексеевна <
***@***.***>:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In task_2-2.c
> <https://github.com/Vyacheslav-TKI/Subutai/pull/7#discussion_r1351743203>:
>
> > +    double x;
> +    double y;
> +    double result;
> +    puts("Enter value of x\n");
> +    if(scanf("%f", &x) != 1){
> +        puts("Please insert a valid value\n");
> +        abort();}
> +
> +    if(a*x < 1){
> +        result = upper_equation(a, x);
> +        printf("X equals: %lf", result);
> +    }
> +    else if(a*x >= 1){
> +        result = lower_equation(a, x);
> +        printf("X equals: %lf", result);
> +    }
>
> @Vyacheslav-TKI <https://github.com/Vyacheslav-TKI> Тогда зачем if 😵‍💫
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Vyacheslav-TKI/Subutai/pull/7#discussion_r1351743203>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOS6THOOFUEZVLHMZVGR6K3X6T4JLAVCNFSM6AAAAAA4WWUSQSVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTMNRWGU3TANJQGQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-10-23 12:03 UTC, MarinaPaley requested changes
Используйте, все же тип `bool`. Это интуитивно понятнее, меньше кода и, вообще, стильно, можно, молодежо!

2023-10-23 12:03 UTC, MarinaPaley commented on task_2-1.c
> +        abort();}
[**NIT:**](https://google.github.io/eng-practices/review/reviewer/standard.html#mentoring) Это [функция `main`](https://en.cppreference.com/w/c/language/main_function), зачем [`abort`](https://en.cppreference.com/w/c/program/abort)? Стоит использовать [`return`](https://en.cppreference.com/w/c/language/return).

2023-10-23 12:03 UTC, MarinaPaley commented on task_2-1.c
> +
Достаточно 1 строки.

2023-10-23 12:03 UTC, MarinaPaley commented on task_2-1.c
> +    }
Ну нет!!! А где же работа с перечислимым типом. У Вас константы в коде!

2023-10-23 12:03 UTC, MarinaPaley commented on task_2-1.c
> +    if(x > 0 && x < 4){
`return (x > 0 && x < 4) ? 1 : 0`
Только зачем это все?

2023-10-23 12:03 UTC, MarinaPaley commented on task_2-1.c
> +    if(x>0){
`return x > 0;` и используйте `bool`

2023-10-23 12:03 UTC, MarinaPaley commented on task_2-1.c
> +    enum Values face = face_area, total = total_surface, volume_cube = volume;
Несогласованность и ... ]кошмар какой-то](https://www.youtube.com/watch?v=uqKrtX6U0n4)!
Зачем Вы снова объявляете тип данных, нужно использовать один &ndash; глобальный.

2023-10-23 12:03 UTC, MarinaPaley commented on task_2-3.c
> +int main(){
Тоже необходима документация!

2023-10-23 12:03 UTC, MarinaPaley commented on task_2-3.c
> +    if (is_pozitive_num(first_side) || is_pozitive_num(second_side) || is_pozitive_num(third_side)){
Заверните в несколько функций (ввод вещественного числа и проверка, что оно положительное)

2023-10-23 12:03 UTC, MarinaPaley commented on task_2-3.c
> +        if((first_side*first_side < second_side*second_side+third_side*third_side) && (second_side*second_side < first_side*first_side+third_side*third_side) && (third_side*third_side < first_side*fi
Выделите в отдельную функцию.

2023-10-23 12:03 UTC, MarinaPaley commented on task_2-3.c
> +
1 строка пропуск.

2023-10-24 07:29 UTC, Vyacheslav-TKI commented on task_2-1.c
> +    if(x>0){
Зачем мне тут использовать bool?

2023-10-24 08:12 UTC, MarinaPaley commented on task_2-1.c
> +    if(x>0){
При использовании `bool` код такой:
```c
retrun x > 0;
```

Без использования &ndash; Ваш велосипед.

2023-11-03 08:17 UTC, BalakinaEP requested changes

2023-11-03 08:17 UTC, BalakinaEP commented on task_2-2.c
> +        printf("X equals: %lf", result);
Печатайте после if. Это же одинаковые строки кода

2023-11-03 08:17 UTC, BalakinaEP commented on task_2-3.c
> +int is_triangle(double first_side, double second_side, double third_side){
Форматирование

2023-11-03 08:17 UTC, BalakinaEP commented on task_2-3.c
> +int is_acute(double first_side, double second_side, double third_side){
Форматирование

2023-11-03 08:17 UTC, BalakinaEP commented on task_2-3.c
> +    if(scanf("%lf", &x) != 1){
Форматирование

2023-11-07 07:21 UTC, Vyacheslav-TKI commented on task_2-3.c
> +    if(scanf("%lf", &x) != 1){
Укажите конкретнее проблему

2023-11-07 07:21 UTC, Vyacheslav-TKI commented on task_2-3.c
> +int is_triangle(double first_side, double second_side, double third_side){
Укажите конкретнее проблему

2023-11-07 07:22 UTC, Vyacheslav-TKI commented on task_2-3.c
> +int is_acute(double first_side, double second_side, double third_side){
Укажите конкретнее проблему

2023-11-07 08:29 UTC, BalakinaEP approved these changes

2024-02-09 10:52 UTC, merged