Задание 3-1 + доп
Vyacheslav-TKI/Subutai pull request #9
Opened 2023-10-21 18:27 UTC by Vyacheslav-TKI

2023-10-23 10:59 UTC, MarinaPaley requested changes
Похвально, что Вы выполняете еще и дополнительные задания!

2023-10-23 10:59 UTC, MarinaPaley commented on 3-1.c
> +int main(){
1. Числовые константы в задании представлены только для выполнения тестового примера. Для решения в общем виде необходимо начало, конец диапазона и шаг расчета ввести с клавиатуры, со всеми проверками.
2. Все задания (12 штук на семестр) должны быть реализованы с применением функций.
3. Все функции, включая `main()` должны иметь документацию в стиле `doxygen`.
4. В процессе расчета может случиться, что функция не имеет значения при некотором аргументе. Такой вариант нужно тоже учитывать (https://www.youtube.com/watch?v=h7hIt2ekYqA)!

2023-10-23 10:59 UTC, MarinaPaley commented on 3-1_addition.c
> +        abort();
1. Это `main()`, отсюда только `return`
2. На лекции было показано, как работать с кодами ошибок. А все, что показано и рассказано на лекциях должно быть отражено в работах.

2023-10-23 10:59 UTC, MarinaPaley commented on 3-1_addition.c
> +        y = (int)y / 10;
Зачем Вы переводите к целому числу?
В С пишут так:
```c
y /= 10;
++counter;
```

2023-10-23 10:59 UTC, MarinaPaley commented on 3-2.c
> +#include <stdio.h>
В задании требуется использовать рекуррентное выражение!

2023-10-30 08:07 UTC, Vyacheslav-TKI commented on 3-1_addition.c
> +        abort();
2. Как коды ошибок связаны с этим заданием?

2023-10-30 08:11 UTC, Vyacheslav-TKI commented on 3-1_addition.c
> +        y = (int)y / 10;
потому что мне нужно именно целочисленное деление

2023-11-07 15:04 UTC, Vyacheslav-TKI commented
в 3-2 во втором пункте всегда будет бесконечность при расходящемся ряде

2023-11-08 09:34 UTC, BalakinaEP requested changes

2023-11-08 09:34 UTC, BalakinaEP commented on 3-1.c
> +    if (x > 0){
используйте DBL_EPSILON

2023-11-08 09:34 UTC, BalakinaEP commented on 3-1.c
> +    while(x < x_stop){
используйте DBL_EPSILON и в таком виде x_stop вообще не входит

2023-11-08 09:34 UTC, BalakinaEP commented on 3-1.c
> +        if (function(x) != -1){
нельзя так сhавнивать числа double. Используйте DBL_EPSILON

2023-11-08 09:34 UTC, BalakinaEP commented on 3-1.c
> +        }
Форматирование :-( (и везде по коду)
else
{
    printf("y: does not exist, x: %.2lf\n", x);
    x = x + dx;
}

2023-11-08 09:47 UTC, BalakinaEP requested changes

2023-11-08 09:47 UTC, BalakinaEP commented on 3-2.c
> +    }
Вынести это в отдельную функцию

2023-11-08 09:47 UTC, BalakinaEP commented on 3-2.c
> +        return 0;
return 0 мы используем если программа сработала верно. А тут вы предполагаете, что у вас ошибка ввода

2023-11-08 09:47 UTC, BalakinaEP commented on 3-2.c
> +        return 0;
Аналогично. Вынести это в отдельную функцию и return 0 в этом случае использовать нельзя

2023-11-08 09:47 UTC, BalakinaEP commented on 3-2.c
> +    while(r*(pow(r+2, 3) / pow(r+1, 4)) >= e){
добавьте учет DBL_EPSILON

2023-11-08 09:47 UTC, BalakinaEP commented on 3-2.c
> +        result += r*(pow(r+2, 3) / pow(r+1, 4));
рекуррентное выражение подразумевает, что вы каждый следующий член последовательности вычисляете через предыдущий. А вы оставили только коэффициент

2023-11-08 09:47 UTC, BalakinaEP commented on 3-2_addition.c
> +        abort();
abort() в main не используется. Уберите эту функцию в отдельную, тем более у вас здесь и ниже один и тот же код!

2023-11-08 09:47 UTC, BalakinaEP commented on 3-2_addition.c
> +
`return 0;`

2023-11-08 09:47 UTC, BalakinaEP commented on 3-2_addition.c
> + * @param b последняя цифра числа
@return -? и выше во всех функциях

2023-11-08 09:47 UTC, BalakinaEP commented on 3-2.c
> +/**
@return -? и во всех остальных функциях

2023-11-20 08:28 UTC, BalakinaEP requested changes
замечания по тексту

2023-11-20 08:28 UTC, BalakinaEP commented on 3-1.c
> +    double x_step = check_number();
шаг положительный

2023-11-20 08:28 UTC, BalakinaEP commented on 3-1.c
> +            puts("Function not defined\n");
при каком х

2023-11-20 08:28 UTC, BalakinaEP commented on 3-1.c
> +    if (x_start > x_stop)
через -DBL_EPSILON

2023-11-20 08:28 UTC, BalakinaEP commented on 3-1_addition.c
> +}
`return 0;`

2023-11-20 08:28 UTC, BalakinaEP commented on 3-2.c
> +    for(int r = 1; r < k; r++)
<=

2023-11-20 08:28 UTC, BalakinaEP commented on 3-2.c
> +        last_elem *= (pow(r+2, 3) / pow(r+1, 4));
```
last_elem *= (pow(r+2, 3) / pow(r+1, 4));
result += last_elem;
```

2023-11-20 08:28 UTC, BalakinaEP commented on 3-2.c
> +    while(last_elem >= e + DBL_EPSILON)
-DBL_EPSILON

2023-11-20 08:28 UTC, BalakinaEP commented on 3-2.c
> +    double result = 8.0f;
=0

2023-11-20 08:28 UTC, BalakinaEP commented on 3-2.c
> +        result += last_elem*(pow(r+2, 3) / pow(r+1, 4));
result += last_elem;

2023-11-21 08:22 UTC, BalakinaEP requested changes

2023-11-21 08:22 UTC, BalakinaEP commented on 3-1.c
> +}
```
bool check_function(double x)
{
    if ((x + cos(powf(x, 0.52)+2) + DBL_EPSILON) < -0.57 + DBL_EPSILON || x < DBL_EPSILON)
    {
        return false;
    }
    return true;
}
```

2023-11-21 08:22 UTC, BalakinaEP commented on 3-1.c
> +    if (x_start - x_stop > -DBL_EPSILON && x_step > -DBL_EPSILON)
поменять условие

2023-11-21 08:22 UTC, BalakinaEP commented on 3-2.c
> +    int n = check_number_int();
проверка, что n>0

2023-11-21 08:22 UTC, BalakinaEP commented on 3-2.c
> +        result += last_elem;
поменять местами

2023-11-21 08:22 UTC, BalakinaEP commented on 3-2.c
> +    double e = check_number_float();
e>0

2023-11-21 08:22 UTC, BalakinaEP commented on 3-2.c
> +    while(last_elem - e >= -DBL_EPSILON)
по модулю

2023-11-21 08:22 UTC, BalakinaEP commented on 3-2_addition.c
> +        abort();
return 1

2023-11-21 08:22 UTC, BalakinaEP commented on 3-2_addition.c
> +        if (hundreds + tens + units == a && units == b){
if (number_of_hundreds(n) + tens_number(n)== a - b && number_of_units(n)== b)

2023-11-21 08:22 UTC, BalakinaEP commented on 3-3.c
> +    double e = pow(40, -5);
константа 
в функцию

2023-11-21 08:22 UTC, BalakinaEP commented on 3-3.c
> +
проверки

2023-11-21 08:22 UTC, BalakinaEP commented on 3-3.c
> +    while (x_past + DBL_EPSILON > e + DBL_EPSILON){
условие через разницу между точным и приближенным значением

2023-11-21 08:22 UTC, BalakinaEP commented on 3-3.c
> +    double result = x, x_past = x;
lastTerm

2023-11-21 08:22 UTC, BalakinaEP commented on 3-3.c
> +        x_past *= -1 * ((pow(x, 2)) * (2 * r + 1) / (2 * r + 3));
```
x_past *= -1 * ((pow(x, 2)) * (2 * r + 1) / (2 * r + 3));  
result += x_past ;
r++;
```

2023-11-24 07:19 UTC, Vyacheslav-TKI commented on 3-2.c
> +    while(last_elem - e >= -DBL_EPSILON)
Зачем? Иначе цикл будет выполняться бесконечно

2023-11-27 07:38 UTC, BalakinaEP requested changes

2023-11-27 07:38 UTC, BalakinaEP commented on 3-1.c
> +    while (x_start <= x_stop)
DBL_EPSILON

2023-11-27 07:38 UTC, BalakinaEP commented on 3-1.c
> +    if ((x + cos(powf(x, 0.52)+2) + DBL_EPSILON) < -0.57 + DBL_EPSILON || x < DBL_EPSILON)
Условие

2023-11-27 07:38 UTC, BalakinaEP commented on 3-1_addition.c
> +    int number, counter = 0;
counter убрать

2023-11-27 07:38 UTC, BalakinaEP commented on 3-2.c
> +    double e = check_number_float();
и не превышает по модулю первый член ряда

2023-11-27 07:38 UTC, BalakinaEP commented on 3-2.c
> +    while(last_elem - e >= -DBL_EPSILON)
fabs(last_elem)

2023-11-27 07:38 UTC, BalakinaEP commented on 3-3.c
> +        result += x_past ;
`result += last_term;`

2023-12-04 07:29 UTC, BalakinaEP requested changes

2023-12-04 07:29 UTC, BalakinaEP commented on 3-2.c
> +    if (x < -DBL_EPSILON && x - fabs((pow(1+2, 3) / pow(1+1, 4))) > DBL_EPSILON)
(x < DBL_EPSILON && x - fabs((pow(1+2, 3) / pow(1+1, 4))) > -DBL_EPSILON)

2023-12-04 07:29 UTC, BalakinaEP commented on 3-3.c
>      while (result_of_function(x) - last_term - e > DBL_EPSILON)
(result_of_function(x) - result - e > -DBL_EPSILON)

2023-12-04 08:18 UTC, BalakinaEP approved these changes

2024-02-09 10:52 UTC, merged